#cloud-config
ssh_authorized_keys:
  - ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAQEA6TiRDiJciqVPEFKIe7/MkBCxgYg7QDnxZDmbQ0pK0TqrEZj/tI0axzQY9qGyXATRGY7VJZK+ZVmKKG+bdsWqSCV6kiRl8EtmSGAOMCz1pfEvHIpqfD2b/gNJPPs8h0Y3xmGpGqme15CK8tRtixRHPwYV/sVGqWKX0sgQ7FnKBZZGYNsR+IJDyr4WewGFkV6FoQFuoE6WGXnRXzsLyyUTpX+VmeWcRqTElb20yQAKwjXEvpgoRR6zRjkpOykcZBL++kVTm9Urk4EOxBDddsaZOR9Wy1EcwjMIUHdE5tJrqHpr7swHZxgK2ZRK+EAgmUkqbKJZLDj1kHrp7tJ7gatUgw==
hostname: mediaboat
rancher: 
  network:
    interfaces:
      eth0:
        address: 10.0.0.11/24
        gateway: 10.0.0.1
        mtu: 1500
        dhcp: false
    dns:
      nameservers:
      - 1.1.1.1
      - 8.8.4.4
